Added code for newer download location

diff --git a/minecrafty b/minecrafty
--- a/minecrafty
+++ b/minecrafty
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 VERSION=0
-MINOR=44
+MINOR=45
 PATCH=
 ME=$(basename $0)
 # Default gamma brightness of game
@@ -349,7 +349,7 @@ FetchMinecraft() {
     # Not yet, as I don't know how to match it up against certain patterns.
     # somepattern is 1[12]w[12345][0-9][a-f], somepattern2 is [12].[0-9].[0-9]
     case $DROPOFF in 
-        1[1234]w[012345][0-9][a-f_]) # snapshot version, should be good for snapshots up to the end of 2014
+        1[12]w[012345][0-9][a-f_]) # snapshot version, should be good for snapshots up to the end of 2012
             if [[ ! -f ${SINGLE}/snapshot_${DROPOFF}.jar ]]; then # only fetch if we haven't got it already
                 wget -O ${SINGLE}/snapshot_$DROPOFF.jar http://assets.minecraft.net/${DROPOFF//\./_}/minecraft.jar
                 retval=$?
@@ -363,7 +363,45 @@ FetchMinecraft() {
             # otherwise, it succeeded, we might as well go get the server file
             wget -O ${SERVER}/snapshot_server_$DROPOFF.jar http://assets.minecraft.net/${DROPOFF//\./_}/minecraft_server.jar
         ;;
-        [12].[0-9].[0-9]|[12].[0-9]) # final version, account for 1.4 and 1.4.3
+		1.5.[2-9]) # New form of final release
+            SINGLE="${MCBase}/versions" # A new home for the release
+    SERVER="${MCBase}/server/stash" # hmm? Does this remain the same?
+            if [[ ! -d ${SINGLE}/${DROPOFF} ]]; then
+			    mkdir -p "${SINGLE}/${DROPOFF}"  # catch the "no .minecraft/versions dir" error
+            fi
+            if [[ ! -f ${SINGLE}/${DROPOFF}/${DROPOFF}.jar ]]; then
+                wget -O "${SINGLE}/${DROPOFF}/${DROPOFF}.jar" http://s3.amazonaws.com/Minecraft.Download/versions/${DROPOFF}/${DROPOFF}.jar
+                retval=$?
+            fi
+            if [[ $retval != 0 ]]; then
+                rm "${SINGLE}/${DROPOFF}/${DROPOFF}.jar"
+                echo "Download failed, no such version or other error"
+                exit 1
+            fi
+			# Plainly, this isn't correct dropoff point any more, but then, where is?
+            wget -O ${SERVER}/final_server_${DROPOFF}.jar http://s3.amazonaws.com/Minecraft.Download/versions/${DROPOFF}/minecraft_server.${DROPOFF}.jar
+
+		;;
+		13w1[6-9][a-f_]|13w[234][0-9][a-f_]|13w5[012][a-f_]|14w[0-5][0-9][a-f_]) # New form of final release
+            SINGLE="${MCBase}/versions" # A new home for the release
+    SERVER="${MCBase}/server/stash" # hmm? Does this remain the same?
+            if [[ ! -d ${SINGLE}/${DROPOFF} ]]; then
+			    mkdir -p "${SINGLE}/${DROPOFF}"  # catch the "no .minecraft/versions dir" error
+            fi
+            if [[ ! -f ${SINGLE}/${DROPOFF}/${DROPOFF}.jar ]]; then
+                wget -O "${SINGLE}/${DROPOFF}/${DROPOFF}.jar" http://s3.amazonaws.com/Minecraft.Download/versions/${DROPOFF}/${DROPOFF}.jar
+                retval=$?
+            fi
+            if [[ $retval != 0 ]]; then
+                rm "${SINGLE}/${DROPOFF}/${DROPOFF}.jar"
+                echo "Download failed, no such version or other error"
+                exit 1
+            fi
+			# Plainly, this isn't correct dropoff point any more, but then, where is?
+            wget -O ${SERVER}/final_server_${DROPOFF}.jar http://s3.amazonaws.com/Minecraft.Download/versions/${DROPOFF}/minecraft_server.${DROPOFF}.jar
+
+		;;
+        1.[01234].[0-9]|[1].[0-5]|1.5.[01]) # final version, account for x.y and x.y.z
             if [[ ! -f ${SINGLE}/final_${DROPOFF}.jar ]]; then
                 wget -O ${SINGLE}/final_$DROPOFF.jar http://assets.minecraft.net/${DROPOFF//\./_}/minecraft.jar
                 retval=$?
@@ -375,6 +413,7 @@ FetchMinecraft() {
             fi
             wget -O ${SERVER}/final_server_$DROPOFF.jar http://assets.minecraft.net/${DROPOFF//\./_}/minecraft_server.jar
         ;;
+
 ##################
 # These options to -f download various launchers, make sure we don't overwrite.
 ##################
