Added new GUI launcher to -l as 'new'

diff --git a/minecrafty b/minecrafty
--- a/minecrafty
+++ b/minecrafty
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 VERSION=0
-MINOR=63
+MINOR=65
 PATCH=
 ME=$(basename $0)
 # Default gamma brightness of game
@@ -17,8 +17,13 @@ CMDOPT=" "
 # If you don't have a java, then you've got problems
 JAVARUN="java"
 CMDRUN="$JAVARUN"
-# Mandatory
+# Mandatory, though this can be OS-dependent
+# MacOsX home: MCBase="~/Library/Application Support/minecraft"
+# Windows (cygwin) Home:  MCBase="%APPDATA%/.minecraft" #(supposedly)
+# Linux Home: MCBase="${HOME}/.minecraft"
 MCBase="${HOME}/.minecraft"
+# Better to patch the new launcher into an existing setup than rewire everything
+NEWCMDRUN="${MCBase}/minecraft-launcher/minecraft-launcher"
 # Set the logfile to empty string initially
 OUTFILE=""
 # Optional, if you add launchers, set a path here, add a SetXyzLauncher()
@@ -100,6 +105,7 @@ LOA=(
 "default" DefaultSettings "run default launcher"
 "launcher" DefaultSettings "run default launcher"
 "vanilla" DefaultSettings "run default launcher"
+"new" NewDefaultSettings "run new default launcher"
 "atl" SetATLauncher "run AT Launcher"
 "ftb" SetFTBLauncher "run FTB launcher"
 "magic" SetMagicLauncher "run MagicLauncher"
@@ -424,6 +430,7 @@ FetchGlobalManifest() {
     wget -O ${MCHOME}/stash/version_manifest.json https://launchermeta.mojang.com/mc/game/version_manifest.json
     # TODO: Please code the fail case!
     # TODO: we should deal with commas at this stage so that searching will work
+    # blank function MassageVersionManifest for that()
 }
 
 # This should fetch the manifest for individual version
@@ -435,6 +442,12 @@ FetchVersionManifest() {
 	DROPOFF_MANIFEST_URL=$(grep ${DROPOFF} ${manifest}| grep URL)
     fi
     wget -O ${DROPOFF}/${DROPOFF}.json ${DROPOFF_MANIFEST_URL}
+}
+
+MassageVersionManifest() {
+    echo "${ME}: doesn't work, please code MassageVersionManifest()"
+    # Blank, but will add CR at each , in the XML file
+    return # TODO: please PLEASE create this
 }
 
 
@@ -548,7 +561,8 @@ FetchMinecraft() {
 
 		;;
         # New form of snapshot release, good up to end of 2029, almost completely replaced by default launcher's fetching
-        13w1[6-9][a-f_]|13w[234][0-9][a-f_]|13w5[012][a-f_]|1[4-9]w[0-4][0-9][a-l_]|1[4-9]w5[0-3][a-l_]|2[0-9]w[0-4][0-9][a-l_]|2[0-9]w5[0-3][a-l_]) 
+#        13w1[6-9][a-f_]|13w[234][0-9][a-f_]|13w5[012][a-f_]|1[4-9]w[0-4][0-9][a-l_]|1[4-9]w5[0-3][a-l_]|2[0-9]w[0-4][0-9][a-l_]|2[0-9]w5[0-3][a-l_]) # original pattern
+        13w1[6-9][a-f_]|13w[234][0-9][a-f_]|13w5[012][a-f_]|1[4-7]w[0-4][0-9][a-l_]|1[4-7]w5[0-3][a-l_]|18w0[0-9][a-l_]|18w1[0-6][a-l_]) # changed because of version download changes
             SINGLE="${MCBase}/versions" # A new home for the release
             SERVER="${MCBase}/server/stash" # hmm? Does this remain the same?
             if [[ ! -d ${SINGLE}/${DROPOFF} ]]; then
@@ -577,7 +591,40 @@ FetchMinecraft() {
             wget -O ${SERVER}/snapshot_server_${DROPOFF}.jar http://s3.amazonaws.com/Minecraft.Download/versions/${DROPOFF}/minecraft_server.${DROPOFF}.jar
 
 		;;
+##################
+# New (2018) snapshot sequences
+##################
+        18w19[a-l_]|18w[2-4][0-9][a-l_]|18w5[0-3][a-l_]|19w[0-4][0-9][a-l_]|19w5[0-3][a-l_]|2[0-9]w[0-4][0-9][a-l_]|2[0-9]w5[0-3][a-l_]) # changed because of version download changes
+            SINGLE="${MCBase}/versions" # A new home for the release
+            SERVER="${MCBase}/server/stash" # hmm? Does this remain the same?
+            if [[ ! -d ${SINGLE}/${DROPOFF} ]]; then
+			    mkdir -p "${SINGLE}/${DROPOFF}"  # catch the "no .minecraft/versions dir" error
+            fi
+            if [[ ! -f ${SINGLE}/${DROPOFF}/${DROPOFF}.jar ]]; then
+# this is where we need to insert the call to FetchMinecraftManifest et al.
+                wget -O "${SINGLE}/${DROPOFF}/${DROPOFF}.jar" http://s3.amazonaws.com/Minecraft.Download/versions/${DROPOFF}/${DROPOFF}.jar
+                retval=$?
+            fi
+            if [[ $retval != 0 ]]; then
+                rm "${SINGLE}/${DROPOFF}/${DROPOFF}.jar"
+		rmdir "${SINGLE}/${DROPOFF}/"
+                echo "Download of snapshot ${DROPOFF} jar failed, no such version or other error"
+                exit 1
+            fi
+            if [[ ! -f ${SINGLE}/${DROPOFF}/${DROPOFF}.json ]]; then
+                wget -O "${SINGLE}/${DROPOFF}/${DROPOFF}.json" http://s3.amazonaws.com/Minecraft.Download/versions/${DROPOFF}/${DROPOFF}.json
+                retval=$?
+            fi
+            if [[ $retval != 0 ]]; then
+                rm "${SINGLE}/${DROPOFF}/${DROPOFF}.json"
+                echo "Download of json failed, no such version or other error"
+                exit 1
+            fi
+			# Plainly, this isn't correct dropoff point any more, but then, where is?
+            wget -O ${SERVER}/snapshot_server_${DROPOFF}.jar http://s3.amazonaws.com/Minecraft.Download/versions/${DROPOFF}/minecraft_server.${DROPOFF}.jar
 
+		;;
+	
 ##################
 # These options to -f download various launchers, make sure we don't overwrite.
 ##################
@@ -708,6 +755,15 @@ FetchMinecraft() {
 DefaultSettings() {
         # We should perhaps unset ${MEM}? Problem is, this is called before Set*Launch is.
         CMDARG="-jar ${MCBase}/bin/minecraft-launcher.jar"
+        CMD="${CMDRUN} ${CMDOPT} ${MEM} ${CMDARG}"
+#        FetchGamma
+#        FetchBright
+}
+
+# New set up for new GUI launcher, not the same as the java launcher
+NewDefaultSettings() {
+        CMDARG=""
+        CMDRUN="${NEWCMDRUN}"
         CMD="${CMDRUN} ${CMDOPT} ${MEM} ${CMDARG}"
 #        FetchGamma
 #        FetchBright
