Updated downloadable version selection, updated README

diff --git a/minecrafty b/minecrafty
--- a/minecrafty
+++ b/minecrafty
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 VERSION=0
-MINOR=52
+MINOR=53
 PATCH=
 ME=$(basename $0)
 # Default gamma brightness of game
@@ -43,14 +43,15 @@ GOA=(
 "m:" SetMonitor "select monitor to apply gamma correction to"
 "r:" SetRefresh "nn.n: set a valid refresh rate for the second monitor, as minecraft has a habit of setting this to the recommended value instead of the value used originally."
 "z:" FetchResolution "XxY: set required resolution (1920x1080 default)"
-"f:" FetchMinecraft "retrieves minecraft.jar or launcher from remote host, '-f help' for more details"
-"l:" Launcher "starts specified launcher, -l help for more details"
-"s:" ServerRun "starts the latest server, supply a filename"
+"f:" FetchMinecraft "retrieves minecraft.jar or launcher from remote host, \`-f help' for more details"
+"l:" Launcher "starts specified launcher, \`-l help' for more details"
+"s:" ServerRun "starts the latest server from \`${MCBASE}/server', supply a filename"
 "v" ShowVersionString "show version string"
 )
 
 # Entries that aren't used at the moment, they're obsolete, I think.
 GONA=(
+"G" LogFile "Capture output into a log file"
 )
 
 # Entries for the -f (fetch) switch
@@ -62,11 +63,11 @@ FOA=(
 "default" Fetch "download default launcher"
 "vanilla" Fetch "download default launcher"
 "craft" Fetch "download Craftland installer for latest Aether prerelease"
-"digiex" Fetch "download DigiEX launcher"
+"digiex" Fetch "download DigiEX launcher (obsolete, may not work)"
 "ftb" Fetch "download FTB launcher"
 "magic" Fetch "download MagicLauncher"
 "multi" Fetch "download MultiMC"
-"skmc" Fetch "download development version of SKMCLauncher.jar"
+"skmc" Fetch "download development version of SKMCLauncher.jar (obsolete, may not work)"
 "technic" Fetch "download beta Technic launcher"
 "terra" Fetch "download beta TerraFirmaCraft launcher (1.5.1 only)"
 "mvc" Fetch "download Minecraft Version Changer from TunkDesign"
@@ -328,9 +329,10 @@ ServerRun() {
     ServerPlace="${MCBase}/server"
     echo "ServerName now set to ${ServerName}"
     if [[ -f ${ServerPlace}/${ServerName} ]]; then
+        # TODO: how do we decide if server requires any more memory?
         CMD="$JAVARUN -Xmx1024M -Xincgc -jar ${ServerPlace}/${ServerName}"
     else
-        echo "We don't have the $1 server here, please download from www.minecraft.net"
+        echo "We don't have the $1 server here, please download from www.minecraft.net, getbukkit.org or spigotmc.org"
         retval=1 #bad doggie, bad, there's no point in continuing any further
         echo "Instead, here's a default launcher"
     fi
@@ -388,7 +390,7 @@ FetchMinecraft() {
     SINGLE="${MCBase}/bin"
     SERVER="${MCBase}/server/stash"
     if [[ ! -d $SINGLE ]]; then
-        echo "Can't save, you don't seem to have a valid minecraft installation!"
+        echo "Can't save, you don't seem to have a valid minecraft installation at ${MCBASE}!"
         # TODO: This needs fixing, so the bash script will create the directory for us.
         exit 1
     fi
@@ -406,6 +408,7 @@ FetchMinecraft() {
     # Not yet, as I don't know how to match it up against certain patterns.
     # somepattern is 1[12]w[12345][0-9][a-f], somepattern2 is [12].[0-9].[0-9]
     case $DROPOFF in 
+        ########## Older releases ########
         1[12]w[012345][0-9][a-f_]) # snapshot version, should be good for snapshots up to the end of 2012
             if [[ ! -f ${SINGLE}/snapshot_${DROPOFF}.jar ]]; then # only fetch if we haven't got it already
                 wget -O ${SINGLE}/snapshot_$DROPOFF.jar http://assets.minecraft.net/${DROPOFF//\./_}/minecraft.jar
@@ -420,7 +423,23 @@ FetchMinecraft() {
             # otherwise, it succeeded, we might as well go get the server file
             wget -O ${SERVER}/snapshot_server_$DROPOFF.jar http://assets.minecraft.net/${DROPOFF//\./_}/minecraft_server.jar
         ;;
-		1.5.[2-9]|1.[6-9]|1.[6789].[0-9]) # New form of final release, covers every single digit version up to just under 2.x
+        # older final version, account for x.y and x.y.z from 1.0 to 1.5.1, different home than below's new version
+        1.[01234].[0-9]|1.[0-5]|1.5.[01]) 
+            if [[ ! -f ${SINGLE}/final_${DROPOFF}.jar ]]; then
+                wget -O ${SINGLE}/final_$DROPOFF.jar http://assets.minecraft.net/${DROPOFF//\./_}/minecraft.jar
+                retval=$?
+            fi
+            if [[ $retval != 0 ]]; then
+                rm ${SINGLE}/final_${DROPOFF}.jar
+                echo "Download of ${DROPOFF} jar failed, no such version or other error"
+                exit 1
+            fi
+            wget -O ${SERVER}/final_server_$DROPOFF.jar http://assets.minecraft.net/${DROPOFF//\./_}/minecraft_server.jar
+        ;;
+        ########## Newer releases ########
+        # New form of final release, covers every single 1.x (1.6 - 1.9) and double digit 1.xx.yy version (1.5.2 up to 1.39.9)
+        # almost completely replaced by default launcher's fetching of every version including ancient ones
+        1.5.[2-9]|1.[6-9]|1.[6789].[0-9]|1.[123][0-9]|1.[123][0-9].[0-9])
             SINGLE="${MCBase}/versions" # A new home for the release
             SERVER="${MCBase}/server/stash" # hmm? Does this remain the same?
             if [[ ! -d ${SINGLE}/${DROPOFF} ]]; then
@@ -448,7 +467,9 @@ FetchMinecraft() {
             wget -O ${SERVER}/final_server_${DROPOFF}.jar http://s3.amazonaws.com/Minecraft.Download/versions/${DROPOFF}/minecraft_server.${DROPOFF}.jar
 
 		;;
-		13w1[6-9][a-f_]|13w[234][0-9][a-f_]|13w5[012][a-f_]|14w[0-5][0-9][a-f_]) # New form of final release
+        # New form of snapshot release, good up to end of 2019, almost completely replaced by default launcher's fetching
+        # TODO: never seems to cover week 53, do we ever need it?
+        13w1[6-9][a-f_]|13w[234][0-9][a-f_]|13w5[012][a-f_]|1[456789]w[0-4][0-9][a-f_]|1[456789]w5[0-2][a-f_]) 
             SINGLE="${MCBase}/versions" # A new home for the release
             SERVER="${MCBase}/server/stash" # hmm? Does this remain the same?
             if [[ ! -d ${SINGLE}/${DROPOFF} ]]; then
@@ -476,18 +497,6 @@ FetchMinecraft() {
             wget -O ${SERVER}/final_server_${DROPOFF}.jar http://s3.amazonaws.com/Minecraft.Download/versions/${DROPOFF}/minecraft_server.${DROPOFF}.jar
 
 		;;
-        1.[01234].[0-9]|[1].[0-5]|1.5.[01]) # final version, account for x.y and x.y.z
-            if [[ ! -f ${SINGLE}/final_${DROPOFF}.jar ]]; then
-                wget -O ${SINGLE}/final_$DROPOFF.jar http://assets.minecraft.net/${DROPOFF//\./_}/minecraft.jar
-                retval=$?
-            fi
-            if [[ $retval != 0 ]]; then
-                rm ${SINGLE}/final_${DROPOFF}.jar
-                echo "Download of ${DROPOFF} jar failed, no such version or other error"
-                exit 1
-            fi
-            wget -O ${SERVER}/final_server_$DROPOFF.jar http://assets.minecraft.net/${DROPOFF//\./_}/minecraft_server.jar
-        ;;
 
 ##################
 # These options to -f download various launchers, make sure we don't overwrite.
@@ -507,7 +516,7 @@ FetchMinecraft() {
         magic) # another non-default launcher
             wget -O ${MCBase}/bin/MagicLauncher-1.0.0.jar http://magiclauncher.com/download.php?f=MagicLauncher_1.0.0.jar
             ;;
-        digiex) # non-default launcher, definitely old
+        digiex) # non-default launcher, definitely ancient
             wget -O ${MCBase}/bin/mclauncher.jar http://minecraft.digiex.org/dlfiles/mclauncher.jar
             ;;
         multi) #yet another non-default, we can't normally download this one directly, it's adfly'd
@@ -517,6 +526,7 @@ FetchMinecraft() {
             grep -qi SUCCESS jobstatus
             retval=$?
             rm jobstatus
+            # TODO: do we need to cover x86_64 too?
             if [[ retval -eq 0 ]]; then
                 wget -O ${MCBase}/bin/MultiMC "http://ci.forkk.net/job/MultiMC4Linux/arch=x86/lastBuild/artifact/MultiMC"
             else
@@ -539,6 +549,7 @@ FetchMinecraft() {
                 # TODO: If this fails, we have bigger problems
             fi
             # TODO: correct this for each version, scrape webpage?
+            # NB: launcher updates itself, and there's now a new version, not yet compat with Linux as of 2015
             wget -O ${FTBBase}/FTB_Loader.jar "http://www.creeperrepo.net/direct/FTB2/697ef1c4d2cb0eddfbf53c3eceba4889/launcher%5EFTB_Launcher.jar"
             ;;
         technic) # Patching in support for Technic_Loader, one of the few to need a different root.
@@ -583,7 +594,7 @@ FetchMinecraft() {
             fi
             wget -O ${ATLauncherBase}/ATLauncher.jar https://www.atlauncher.com/download/jar
             ;;
-        *) echo "Can't recognise $1 (yet). minecrafty -f help for further details."
+        *) echo "Can't recognise $1 (yet). minecrafty -f help for stuff I can fetch."
             exit 1
             ;;
     esac
@@ -690,7 +701,7 @@ SetCraftLauncher() {
 }
 
 SetDigiLauncher() {
-# runs mclauncher
+# runs  digiexs' mclauncher
     CMDRUN="$PARUN $JAVARUN -Xincgc"
     CMDARG="-jar ${MCBase}/bin/mclauncher.jar"
     CMD="${CMDRUN} ${CMDOPT} ${MEM} ${CMDARG}"
@@ -836,11 +847,14 @@ done
 
 }
 
+# End of functions, now let's create our arrays
+
 StuffGetOpts
 StuffFetchOpts
 StuffLaunchOpts
 StuffCommands
 
+# Stuffed arrays? Now let's do something with them
 case $1 in "-?"|"-h") Help
 exit 0
 ;;
